config/routes.rb
IE::Application.routes.draw do
  resources :broadcasts

  resources :topics

  resources :classtimes

  resources :users
  root to: 'pages#home'
  get "pages/home"
  get "pages/home" => "pages#home"
  get "search" => "pages#search"
  get "student" => "pages#student"
  get "sisley" => "pages#sisley"
  
  get "broadcast"=> "pages#broadcast"
  
  post "loadUser" => "pages#loadUser"
  post "exportUser" => "users#exportUser"
  post "loadTopic" => "pages#loadTopic"
  post "loadClassTime" => "pages#loadClassTime"
  
  get "backSisley" => "pages#backSisley"
  
  get "resetUser" => "pages#resetUser"
  get "resetClasstime" => "pages#resetClasstime"
  get "resetTopic" => "pages#resetTopic"
  
  get "/pages/dbadmin" => "pages#dbadmin"
  
  get "searchUser" => "users#search"
  get "searchClasstime" => "classtimes#search"

end

app/models/classtime.rb
class Classtime < ActiveRecord::Base
  def self.to_csv(options = {})
      CSV.generate(options) do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
    end
    
    
    def self.import_data(csv)    
      CSV.parse(csv) do |row|
        name = String(row[0])
        password = String(row[1])
        totalTime = String(row[2])
        takenTime = String(row[3])
        balance = String(row[4])
        vipbalance = String(row[5])
        givenVIPtime = String(row[6])
        takenVIPTime = String(row[7])
        lastClass = String(row[8])
        validDate = String(row[9])
        self.create(:name => name, :password => password, :totalTime => totalTime, :takenTime => takenTime, :balance => balance, :VIPbalance => vipbalance,
        :givenVIPtime => givenVIPtime, :takenVIPTime => takenVIPTime, :lastClass => lastClass, :validDate => validDate)
      end
    end
  
end

app/controllers/classtimes_controller.rb
class ClasstimesController < ApplicationController
  before_action :set_classtime, only: [:show, :edit, :update, :destroy]

  # GET /classtimes
  # GET /classtimes.json
  def index
    @classtimes = Classtime.all
    if params[:p] != "success"
      render 'pages/db'
    end
  end
  
  def exportClasstime
    @classtimes = Classtime.all
    respond_to do |format|
      format.html
      format.xls  { send_data @products.to_csv(col_sep: "\t") }
    end
    render "index"
  end
  
  def search
    name = params[:name]
    @classtimes = Classtime.where("name = ?", name).select('*')
    render "index"
  end
  
  # GET /classtimes/1
  # GET /classtimes/1.json
  def show
  end

  # GET /classtimes/new
  def new
    @classtime = Classtime.new
  end

  # GET /classtimes/1/edit
  def edit
    #name = params[:name]
    #password = params[:password]
    #totalTime = params[:totalTime]
    #takenTime = params[:takenTime]
    #vipbalance = params[:VIPbalance]
    #givenVIPtime = params[:givenVIPtime]
    #takenVIPTime = params[:takenVIPTime]
    #validDate = params[:validDate]
    #balance = totalTime - takenTime
    #lastClass = Time.new
    #@classtime.update_attributes(:name => name,:password => password, :totalTime => totalTime, :takenTime => takenTime,
    #:balance => balance, :VIPbalance => vipbalance, :givenVIPtime => givenVIPtime, :takenVIPTime => takenVIPTime, :lastClass => lastClass,
    #:validDate => validDate)
  end


  # POST /classtimes
  # POST /classtimes.json
  def create
    @classtime = Classtime.new(classtime_params)
    respond_to do |format|
      if @classtime.save
        format.html { redirect_to @classtime, notice: 'Classtime was successfully created.' }
        format.json { render action: 'show', status: :created, location: @classtime }
      else
        format.html { render action: 'new' }
        format.json { render json: @classtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classtimes/1
  # PATCH/PUT /classtimes/1.json
  def update
    respond_to do |format|
      if @classtime.update(classtime_params)
        format.html { redirect_to @classtime, notice: 'Classtime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @classtime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classtimes/1
  # DELETE /classtimes/1.json
  def destroy
    @classtime.destroy
    respond_to do |format|
      format.html { redirect_to classtimes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_classtime
    @classtime = Classtime.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def classtime_params
    params.require(:classtime).permit(:name, :password, :totalTime, :takenTime, :balance, :VIPbalance, :givenVIPtime, :takenVIPTime, :lastClass, :validDate)
  end
end

app/helpers/classtimes_helper.rb
module ClasstimesHelper
end

app/views/classtimes/_form.html.erb
<%= form_for(@classtime) do |f| %>
  <% if @classtime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classtime.errors.count, "error") %> prohibited this classtime from being saved:</h2>

      <ul>
      <% @classtime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :totalTime %><br />
    <%= f.number_field :totalTime %>
  </div>
  <div class="field">
    <%= f.label :takenTime %><br />
    <%= f.number_field :takenTime %>
  </div>
  <div class="field">
    <%= f.label :balance %><br />
    <%= f.number_field :balance %>
  </div>
  <div class="field">
    <%= f.label :VIPbalance %><br />
    <%= f.number_field :VIPbalance %>
  </div>
  <div class="field">
    <%= f.label :givenVIPtime %><br />
    <%= f.text_field :givenVIPtime %>
  </div>
  <div class="field">
    <%= f.label :takenVIPTime %><br />
    <%= f.number_field :takenVIPTime %>
  </div>
  <div class="field">
    <%= f.label :lastClass %><br />
    <%= f.text_field :lastClass %>
  </div>
  <div class="field">
    <%= f.label :validDate %><br />
    <%= f.text_field :validDate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classtimes/db.html.erb
<%= form_tag("/pages/dbadmin", :method => "get") do %>
  <%= label_tag(:t, "Password:") %>
<%= password_field_tag(name = :password) %>
  <%= submit_tag("Go!") %>
<% end %>
</br>
<%= @error%>

app/views/classtimes/edit.html.erb
<h1>Editing classtime</h1>
<%= render 'form' %>
<%= link_to 'Show', @classtime %> |
<%= link_to 'Back', classtimes_path(:p => "success") %>

app/views/classtimes/index.html.erb
<h1>Listing classtimes</h1>
<form action="backSisley" method="get">
<button class="btn parkBtn" id="backSisley">返回Sisley专属页面</button>
</form>

<form action="searchClasstime" method="get">
	<input type="text" name="name" class="insty" required></input>
	<button id="searchBtn" class="btn parkBtn">查询学生</button>
</form>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Totaltime</th>
      <th>Takentime</th>
      <th>Balance</th>
      <th>Vipbalance</th>
      <th>Givenviptime</th>
      <th>Takenviptime</th>
      <th>Lastclass</th>
      <th>Validdate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @classtimes.each do |classtime| %>
    <tr>
      <td><%= classtime.name %></td>
      <td><%= classtime.password %></td>
      <td><%= classtime.totalTime %></td>
      <td><%= classtime.takenTime %></td>
      <td><%= classtime.balance %></td>
      <td><%= classtime.VIPbalance %></td>
      <td><%= classtime.givenVIPtime %></td>
      <td><%= classtime.takenVIPTime %></td>
      <td><%= classtime.lastClass %></td>
      <td><%= classtime.validDate %></td>
      <td><%= link_to 'Show', classtime %></td>
      <td><%= link_to 'Edit', edit_classtime_path(classtime) %></td>
      <td><%= link_to 'Destroy', classtime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Classtime', new_classtime_path %>

app/views/classtimes/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:html="http://www.w3.org/TR/REC-html40">
<Worksheet ss:Name="Sheet1">
	<Table>
		<Row>
			<Cell><Data ss:Type="String">Name</Data></Cell>
			<Cell><Data ss:Type="String">Password</Data></Cell>
			<Cell><Data ss:Type="String">Total_time</Data></Cell>
			<Cell><Data ss:Type="String">Taken_time</Data></Cell>
			<Cell><Data ss:Type="String">Balance</Data></Cell>
			<Cell><Data ss:Type="String">VIP_balance</Data></Cell>
			<Cell><Data ss:Type="String">Taken_VIP_time</Data></Cell>
			<Cell><Data ss:Type="String">Last_class</Data></Cell>
			<Cell><Data ss:Type="String">Valid_date</Data></Cell>
			 
		</Row>
		<% @classtimes.each do |product| %>
		<Row>
			<Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.password %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.totalTime %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.takenTime %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.balance %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.VIPbalance %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.takenVIPTime %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.lastClass %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.validDate %></Data></Cell>
		</Row>
		<% end %>
	</Table>
</Worksheet>
</Workbook>

app/views/classtimes/new.html.erb
<h1>New classtime</h1>

<%= render 'form' %>

<%= link_to 'Back', classtimes_path(:p => "success") %>

app/views/classtimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classtime.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @classtime.password %>
</p>

<p>
  <strong>Totaltime:</strong>
  <%= @classtime.totalTime %>
</p>

<p>
  <strong>Takentime:</strong>
  <%= @classtime.takenTime %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @classtime.balance %>
</p>

<p>
  <strong>Vipbalance:</strong>
  <%= @classtime.VIPbalance %>
</p>

<p>
  <strong>Givenviptime:</strong>
  <%= @classtime.givenVIPtime %>
</p>

<p>
  <strong>Takenviptime:</strong>
  <%= @classtime.takenVIPTime %>
</p>

<p>
  <strong>Lastclass:</strong>
  <%= @classtime.lastClass %>
</p>

<p>
  <strong>Validdate:</strong>
  <%= @classtime.validDate %>
</p>


<%= link_to 'Edit', edit_classtime_path(@classtime) %> |
<%= link_to 'Back', classtimes_path(:p => "success") %>