config/routes.rb
IE::Application.routes.draw do
  resources :broadcasts

  resources :topics

  resources :classtimes

  resources :users
  root to: 'pages#home'
  get "pages/home"
  get "pages/home" => "pages#home"
  get "search" => "pages#search"
  get "student" => "pages#student"
  get "sisley" => "pages#sisley"
  
  get "broadcast"=> "pages#broadcast"
  
  post "loadUser" => "pages#loadUser"
  post "exportUser" => "users#exportUser"
  post "loadTopic" => "pages#loadTopic"
  post "loadClassTime" => "pages#loadClassTime"
  
  get "backSisley" => "pages#backSisley"
  
  get "resetUser" => "pages#resetUser"
  get "resetClasstime" => "pages#resetClasstime"
  get "resetTopic" => "pages#resetTopic"
  
  get "/pages/dbadmin" => "pages#dbadmin"
  
  get "searchUser" => "users#search"
  get "searchClasstime" => "classtimes#search"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        csv << user.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.import_data(csv)    
    CSV.parse(csv) do |row|
      year = String(row[0])
      month = String(row[1])
      day = String(row[2])
      startTime = String(row[3])
      endTime = String(row[4])
      people = String(row[5])
      theme = String(row[6])
      preparation = String(row[7])
      homework = String(row[8])
      self.create(:year => year, :month => month, :day => day, :startTime => startTime, :endTime => endTime, :people => people, :theme => theme, 
      :preparation => preparation, :homework => homework)
    end
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    if params[:p] != "success"
      render 'pages/db'
    end
  end
  
  def exportTopic
    @topics = Topic.all
    respond_to do |format|
      format.html
      format.xls  { send_data @products.to_csv(col_sep: "\t") }
    end
    render "index"
  end
  
  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:year, :month, :day, :startTime, :endTime, :people, :theme, :preparation, :homework)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :month %><br />
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :startTime %><br />
    <%= f.text_field :startTime%>
  </div>
  <div class="field">
    <%= f.label :endTime %><br />
   <%= f.text_field :endTime%>
  </div>
  <div class="field">
    <%= f.label :people %><br />
    <%= f.text_field :people %>
  </div>
  <div class="field">
    <%= f.label :theme %><br />
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :preparation %><br />
    <%= f.text_field :preparation %>
  </div>
  <div class="field">
    <%= f.label :homework %><br />
    <%= f.text_field :homework %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/db.html.erb
<%= form_tag("/pages/dbadmin", :method => "get") do %>
  <%= label_tag(:t, "Password:") %>
<%= password_field_tag(name = :password) %>
  <%= submit_tag("Go!") %>
<% end %>
</br>
<%= @error%>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path(:p => "success")%>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<form action="backSisley" method="get">
<button class="btn parkBtn" id="backSisley">返回Sisley专属页面</button>
</form>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Month</th>
      <th>Day</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>People</th>
      <th>Theme</th>
      <th>Preparation</th>
      <th>Homework</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
    <tr>
      <td><%= topic.year %></td>
      <td><%= topic.month %></td>
      <td><%= topic.day %></td>
      <td><%= topic.startTime %></td>
      <td><%= topic.endTime %></td>
      <td><%= topic.people %></td>
      <td><%= topic.theme %></td>
      <td><%= topic.preparation %></td>
      <td><%= topic.homework %></td>
      <td><%= link_to 'Show', topic %></td>
      <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
xmlns:html="http://www.w3.org/TR/REC-html40">
<Worksheet ss:Name="Sheet1">
	<Table>
		t.string :year
		t.string :month
		t.string :day
		t.string :startTime
		t.string :endTime
		t.string :people
		t.string :theme
		t.string :preparation
		t.string :homework
		<Row>
			<Cell><Data ss:Type="String">Year</Data></Cell>
			<Cell><Data ss:Type="String">Month</Data></Cell>
			<Cell><Data ss:Type="String">Day</Data></Cell>
			<Cell><Data ss:Type="String">Start_time</Data></Cell>
			<Cell><Data ss:Type="String">End_time</Data></Cell>
			<Cell><Data ss:Type="String">People</Data></Cell>
			<Cell><Data ss:Type="String">Theme</Data></Cell>
			<Cell><Data ss:Type="String">Preparation</Data></Cell>
			<Cell><Data ss:Type="String">Homework</Data></Cell>
		</Row>
		<% @topics.each do |product| %>
		<Row>
			<Cell><Data ss:Type="String"><%= product.year %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.month %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.day %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.startTime %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.endTime %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.people %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.theme %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.preparation %></Data></Cell>
			<Cell><Data ss:Type="String"><%= product.homework %></Data></Cell>
		</Row>
		<% end %>
	</Table>
</Worksheet>
</Workbook>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path(:p => "success") %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @topic.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @topic.month %>
</p>

<p>
  <strong>Day:</strong>
  <%= @topic.day %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @topic.startTime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @topic.endTime %>
</p>

<p>
  <strong>People:</strong>
  <%= @topic.people %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @topic.theme %>
</p>

<p>
  <strong>Preparation:</strong>
  <%= @topic.preparation %>
</p>

<p>
  <strong>Homework:</strong>
  <%= @topic.homework %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path(:p => "success") %>