config/routes.rb
IE::Application.routes.draw do
  resources :broadcasts

  resources :topics

  resources :classtimes

  resources :users
  root to: 'pages#home'
  get "pages/home"
  get "pages/home" => "pages#home"
  get "search" => "pages#search"
  get "student" => "pages#student"
  get "sisley" => "pages#sisley"
  
  get "broadcast"=> "pages#broadcast"
  
  post "loadUser" => "pages#loadUser"
  post "exportUser" => "users#exportUser"
  post "loadTopic" => "pages#loadTopic"
  post "loadClassTime" => "pages#loadClassTime"
  
  get "backSisley" => "pages#backSisley"
  
  get "resetUser" => "pages#resetUser"
  get "resetClasstime" => "pages#resetClasstime"
  get "resetTopic" => "pages#resetTopic"
  
  get "/pages/dbadmin" => "pages#dbadmin"
  
  get "searchUser" => "users#search"
  get "searchClasstime" => "classtimes#search"

end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
  before_action :set_broadcast, only: [:show, :edit, :update, :destroy]

  # GET /broadcasts
  # GET /broadcasts.json
  def index
    @broadcasts = Broadcast.all
  end

  # GET /broadcasts/1
  # GET /broadcasts/1.json
  def show
  end

  # GET /broadcasts/new
  def new
    @broadcast = Broadcast.new
  end

  # GET /broadcasts/1/edit
  def edit
  end

  # POST /broadcasts
  # POST /broadcasts.json
  def create
    @broadcast = Broadcast.new(broadcast_params)

    respond_to do |format|
      if @broadcast.save
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully created.' }
        format.json { render action: 'show', status: :created, location: @broadcast }
      else
        format.html { render action: 'new' }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /broadcasts/1
  # PATCH/PUT /broadcasts/1.json
  def update
    respond_to do |format|
      if @broadcast.update(broadcast_params)
        format.html { redirect_to @broadcast, notice: 'Broadcast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @broadcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /broadcasts/1
  # DELETE /broadcasts/1.json
  def destroy
    @broadcast.destroy
    respond_to do |format|
      format.html { redirect_to broadcasts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_broadcast
      @broadcast = Broadcast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def broadcast_params
      params.require(:broadcast).permit(:content)
    end
end

app/helpers/broadcasts_helper.rb
module BroadcastsHelper
end

app/views/broadcasts/_form.html.erb
<%= form_for(@broadcast) do |f| %>
  <% if @broadcast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@broadcast.errors.count, "error") %> prohibited this broadcast from being saved:</h2>

      <ul>
      <% @broadcast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/broadcasts/edit.html.erb
<h1>Editing broadcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @broadcast %> |
<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/index.html.erb
<h1>Listing broadcasts</h1>
<form action="backSisley" method="get">
<button class="btn parkBtn" id="backSisley">返回Sisley专属页面</button>
</form>
<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @broadcasts.each do |broadcast| %>
    <tr>
      <td><%= broadcast.content %></td>
      <td><%= link_to 'Show', broadcast %></td>
      <td><%= link_to 'Edit', edit_broadcast_path(broadcast) %></td>
      <td><%= link_to 'Destroy', broadcast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Broadcast', new_broadcast_path %>

app/views/broadcasts/new.html.erb
<h1>New broadcast</h1>

<%= render 'form' %>

<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @broadcast.content %>
</p>


<%= link_to 'Edit', edit_broadcast_path(@broadcast) %> |
<%= link_to 'Back', broadcasts_path %>